adding load_balancer
venkatsaik/Automating-AWS-with-Terraform pull request #13
Opened 2023-03-27 18:29 UTC by venkatsaik

2023-03-28 15:24 UTC, geoffrey1330 requested changes

2023-03-28 15:24 UTC, geoffrey1330 commented on level-2/load_balancer.tf
> +  port              = "443"
could you please change the port to 80 as we are currently making use of http.

2023-03-28 15:24 UTC, geoffrey1330 commented on level-2/load_balancer.tf
> +  protocol          = "HTTPS"
Also change the protocol to **"HTTP"**

2023-03-29 17:35 UTC, venkatsaik commented
Completed the requested changes.

2023-03-29 18:12 UTC, geoffrey1330 approved these changes

2023-03-29 18:14 UTC, merged